<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>nicoco007.BeatSaberModdingTools.Tasks</PackageId>
        <Title>BeatSaberModdingTools.Tasks</Title>
        <Version>0.1.0</Version>
        <Authors>Zingabopp</Authors>
        <Company>Zingabopp</Company>
        <Description>A set of MSBuild Tasks created for Beat Saber Modding Tools.</Description>
        <Copyright>Copyright © Zingabopp 2020</Copyright>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <RepositoryType>git</RepositoryType>
        <PackageProjectUrl>https://github.com/nicoco007/BeatSaberModdingTools.Tasks</PackageProjectUrl>
        <RepositoryUrl>https://github.com/nicoco007/BeatSaberModdingTools.Tasks.git</RepositoryUrl>
        <LangVersion>8</LangVersion>
    </PropertyGroup>

    <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    </PropertyGroup>

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <RootNamespace>BeatSaberModdingTools.Tasks</RootNamespace>
        <AssemblyName>BeatSaberModdingTools.Tasks</AssemblyName>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <IsPackable>true</IsPackable>
        <IsTestProject>false</IsTestProject>
        <BuildOutputTargetFolder>tasks</BuildOutputTargetFolder>
        <Platforms>AnyCPU</Platforms>
        <!-- Optional: Publish the repository URL in the built .nupkg (in the NuSpec <Repository> element) -->
        <PublishRepositoryUrl>true</PublishRepositoryUrl>

        <!-- Optional: Embed source files that are not tracked by the source control manager in the PDB -->
        <EmbedUntrackedSources>true</EmbedUntrackedSources>

        <!-- Optional: Build symbol package (.snupkg) to distribute the PDB containing Source Link -->
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <developmentDependency>true</developmentDependency>
        <NoWarn>NU5100</NoWarn>
    </PropertyGroup>

    <PropertyGroup>
        <DocumentationFile>BeatSaberModdingTools.Tasks.xml</DocumentationFile>
        <PackageTags>Beat Saber;BeatSaberModdingTools</PackageTags>
        <PackageReadmeFile>package_readme.md</PackageReadmeFile>
        <PackageReleaseNotes>
            * Converted to new GitHub Actions environment files for output
            * Added new SetActionOutput Task
            * Added option to disable embedding generated manifests
            * GameVersion is also an output for GenerateManifest (for when it's defined by an existing manifest)
        </PackageReleaseNotes>
        <PackageIcon>bsmt.tasks_icon.png</PackageIcon>
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    </PropertyGroup>

    <ItemGroup>
        <None Include="package_readme.md" Pack="true" PackagePath="\" />
        <Content Include="BeatSaberModdingTools.Tasks.props" Pack="true" PackagePath="build\$(PackageId).props" />
        <Content Include="BeatSaberModdingTools.Tasks.targets" Pack="true" PackagePath="build\$(PackageId).targets" />
        <Content Include="BuildTypes\BSMT.BSIPA.props" Pack="true" PackagePath="build\BuildTypes\BSMT.BSIPA.props" />
        <Content Include="BuildTypes\BSMT.BSIPA.targets" Pack="true" PackagePath="build\BuildTypes\BSMT.BSIPA.targets" />
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="nupkgs\**" />
        <EmbeddedResource Remove="nupkgs\**" />
        <None Remove="nupkgs\**" />
        <None Remove="BuildTypes\BSMT.BSIPA.targets" />
        <None Include="..\LICENSE">
            <Pack>True</Pack>
            <PackagePath></PackagePath>
        </None>
        <None Include="bsmt.tasks_icon.png">
            <Pack>True</Pack>
            <PackagePath></PackagePath>
        </None>
    </ItemGroup>

    <ItemGroup Condition="'$(ContinuousIntegrationBuild)' == 'True'">
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0" PrivateAssets="All" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Build.Framework" Version="17.11.31" />
        <PackageReference Include="Microsoft.Build.Tasks.Core" Version="17.11.31" />
        <PackageReference Include="System.Diagnostics.Process" Version="4.3.0" />
    </ItemGroup>

    <Target Name="GithubActionsInfo" AfterTargets="Pack">
        <PropertyGroup Condition="'$(GITHUB_OUTPUT)' == ''">
            <GITHUB_OUTPUT>test.txt</GITHUB_OUTPUT>
        </PropertyGroup>
        <ItemGroup>
            <GithubOutputs Include="filename=$(AssemblyName)-$(PackageVersion)" />
            <GithubOutputs Include="assemblyname=$(AssemblyName)" />
        </ItemGroup>
        <Message Text="Writing to environment file: $(GITHUB_OUTPUT)" Importance="high" />
        <WriteLinesToFile File="$(GITHUB_OUTPUT)" Lines="@(GithubOutputs)" Encoding="Unicode" />
    </Target>
    <Target Name="CopyToLocalNuget" AfterTargets="Pack" Condition="'$(ContinuousIntegrationBuild)' != 'True'">
        <Exec Command="$(USERPROFILE)\.nuget\nuget.exe delete $(PackageId) $(PackageVersion) -Source &quot;$(USERPROFILE)\.nuget\packages&quot; -NonInteractive" IgnoreExitCode="true" />
        <Exec Command="$(USERPROFILE)\.nuget\nuget.exe delete $(PackageId) $(PackageVersion) -Source &quot;$(USERPROFILE)\.nuget\local&quot; -NonInteractive" IgnoreExitCode="true" />
        <Exec Command="$(USERPROFILE)\.nuget\nuget.exe add &quot;$(ProjectDir)$(PackageOutputPath)$(PackageId).$(PackageVersion).nupkg&quot; -Source &quot;$(USERPROFILE)\.nuget\local&quot;" />
    </Target>
</Project>
