<!-- 
  This file is automatically imported by NuGet into a user's project
  when it targets a single framework, or in classic (pre 2017) csproj projects.
-->
<!--<Project TreatAsLocalProperty="BSMTTaskFolder;BSMTTaskAssembly" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">-->
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup>
        <BSMTProjectType Condition="'$(BSMTProjectType)' == ''">BSIPA</BSMTProjectType>
    </PropertyGroup>

    <PropertyGroup>
        <BSMTTaskFolder>netstandard2.0</BSMTTaskFolder>
        <IsNetCoreApp Condition="$(MSBuildRuntimeType) == 'Core'">true</IsNetCoreApp>
        <IsNetCoreApp Condition="$(MSBuildRuntimeType) != 'Core'">false</IsNetCoreApp>
        <BSMTTaskAssembly>$(MSBuildThisFileDirectory)..\tasks\$(BSMTTaskFolder)\BeatSaberModdingTools.Tasks.dll</BSMTTaskAssembly>
    </PropertyGroup>

    <UsingTask TaskName="BeatSaberModdingTools.Tasks.CompareVersions" AssemblyFile="$(BSMTTaskAssembly)" TaskFactory="TaskHostFactory" />
    <UsingTask TaskName="BeatSaberModdingTools.Tasks.GetAssemblyInfo" AssemblyFile="$(BSMTTaskAssembly)" TaskFactory="TaskHostFactory" />
    <UsingTask TaskName="BeatSaberModdingTools.Tasks.GetCommitInfo" AssemblyFile="$(BSMTTaskAssembly)" TaskFactory="TaskHostFactory" />
    <UsingTask TaskName="BeatSaberModdingTools.Tasks.GetManifestInfo" AssemblyFile="$(BSMTTaskAssembly)" TaskFactory="TaskHostFactory" />
    <UsingTask TaskName="BeatSaberModdingTools.Tasks.IsProcessRunning" AssemblyFile="$(BSMTTaskAssembly)" TaskFactory="TaskHostFactory" />
    <UsingTask TaskName="BeatSaberModdingTools.Tasks.ReplaceInFile" AssemblyFile="$(BSMTTaskAssembly)" TaskFactory="TaskHostFactory" />
    <UsingTask TaskName="BeatSaberModdingTools.Tasks.ZipDir" AssemblyFile="$(BSMTTaskAssembly)" TaskFactory="TaskHostFactory" />
    <UsingTask TaskName="BeatSaberModdingTools.Tasks.GenerateManifest" AssemblyFile="$(BSMTTaskAssembly)" TaskFactory="TaskHostFactory" />
    <UsingTask TaskName="BeatSaberModdingTools.Tasks.SetActionOutput" AssemblyFile="$(BSMTTaskAssembly)" TaskFactory="TaskHostFactory" />

    <Import Project="$(MSBuildThisFileDirectory)BuildTypes\BSMT.BSIPA.props" Condition="'$(BSMTProjectType)' == 'BSIPA'"/>
</Project>