<?xml version="1.0" encoding="utf-8" ?>
<Project>
    <!-- All BSMT targets should DependsOnTargets one of these. -->
    <Target Name="BSMT_BeforeBuild" BeforeTargets="Build" />
    <Target Name="BSMT_AfterBuild" AfterTargets="Build" />

    <Import Project="$(MSBuildThisFileDirectory)BuildTypes\BSMT.BSIPA.targets" Condition="'$(BSMTProjectType)' == 'BSIPA'"/>
    <Import Project="$(MSBuildThisFileDirectory)BuildTypes\BSMT.Test.targets" Condition="'$(BSMTProjectType)' == 'Test'"/>
</Project>