name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      id: build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal --logger GitHubActions
    - name: Pack
      run: dotnet pack ./BeatSaberModdingTools.Tasks/BeatSaberModdingTools.Tasks.csproj -c Release -o ./artifacts --no-restore --include-symbols
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.build.outputs.filename }}
        path: ./artifacts
    - name: Push NuGet package
      if: github.ref_type == 'tag'
      run: |
        dotnet nuget push ./artifacts/*.nupkg --source ${{ secrets.NUGET_SOURCE }} --api-key ${{ secrets.NUGET_KEY }}
